/*
 * OpenAPI User API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

type UsersResponse struct {

	Data []User `json:"data,omitempty"`
}
